name: codenova_reminders
description: your own daily assistant.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.16.1
  rxdart: ^0.24.1
  flutter_local_notifications: ^1.4.4+2
  shared_preferences: ^0.5.7+3
  introduction_screen: ^1.0.9
  lottie: ^0.5.1
  weekday_selector: ^0.4.0
  day_night_time_picker: ^0.2.1
  flashy_tab_bar: ^0.0.3
  modal_bottom_sheet: ^0.2.0+1
  flutter_colorpicker: ^0.3.4
  flutter_rounded_date_picker: ^1.0.4
  emoji_picker: ^0.1.0
  flutter_switch: ^0.1.0
  auto_animated: ^2.1.0
  grouped_buttons: ^1.0.4
  table_calendar: ^2.2.3
  collection: ^1.14.13
  easy_localization: ^2.3.3
  theme_provider: ^0.4.0+1
  share_it: ^0.5.1+3
  fl_chart: ^0.11.0
  line_awesome_icons: ^1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans/ProductSans-Bold.ttf
          weight: 700
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy/Kantumruy-Regular.ttf
        - asset: assets/fonts/Kantumruy/Kantumruy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kantumruy/Kantumruy-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
